# Spring properties
spring:
  application:
    name: api-gateway  # Identify this application

# Server
server:
  port: 8800   # HTTP (Tomcat) port

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION

zuul:
  prefix: /api
  routes:
    user:
      path: /user/**
      url: http://localhost:9901
      stripPrefix: false
      serviceId: user-service
      sensitiveHeaders: Cookie,Set-Cookie
    product:
      path: /product/**
      url: http://localhost:9902
      stripPrefix: false
      serviceId: product-service
      sensitiveHeaders: Cookie,Set-Cookie

ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 990000
  maxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: false
